### ISSUE TITLE
Error with upstream

### ISSUE THREAD

**Issue by ValentinFunk** [debops/ansible-docker#38]
I'm trying to install docker upstream on a few servers using the following playbook (pretty much identical to example one):
```yaml
- name: Configure Backend Servers
  hosts: backend_hosts
  become: True
  vars:
     - ferm__ansible_controllers: ['0.0.0.0/0'] # Disable ferm ssh access filter
  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'
  pre_tasks:
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes
        
  roles:
    - role: "debops.etc_services"
      tags: [ 'role::etc_services' ]
      etc_services__dependent_list:
        - '{{ docker__etc_services__dependent_list }}'

    - role: "debops.ferm"
      ferm__dependent_rules:
        - '{{ docker__ferm__dependent_rules }}'
        
    - role: "debops.docker"
      docker__upstream: True
      tags: [ 'role::docker' ]
```

Unfortunately i run into this error: 
```
RUNNING HANDLER [debops.ferm : Restart ferm] ***********************************
changed: [staging]
changed: [production]

RUNNING HANDLER [debops.docker : Restart docker] *******************************
fatal: [staging]: FAILED! => {"changed": false, "failed": true, "msg": "Warning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' recomm
ended.\nWarning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' recommended.\nJob for docker.service failed. See 'systemctl status doc
ker.service' and 'journalctl -xn' for details.\n"}
fatal: [production]: FAILED! => {"changed": false, "failed": true, "msg": "Warning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' rec
ommended.\nWarning: Unit file of docker.service changed on disk, 'systemctl daemon-reload' recommended.\nJob for docker.service failed. See 'systemctl status
docker.service' and 'journalctl -xn' for details.\n"}
```
